export interface StoryCoverArt {
  themeColor: string;
  accentColor: string;
  gradient: string;
  iconType: "idol" | "chaebol" | "ceo" | "superstar" | "bodyguard" | "revenge" | "time" | "mask" | "camera" | "contract" | "romance";
  tagline: string;
  taglineId: string;
  motif: string;
}

export const STORY_COVERS: Record<string, StoryCoverArt> = {
  "i-married-my-enemy": {
    themeColor: "#881337",
    accentColor: "#E2B714",
    gradient: "linear-gradient(135deg, #4C0519 0%, #1C1917 50%, #1E1B4B 100%)",
    iconType: "contract",
    tagline: "A dangerous marriage of convenience.",
    taglineId: "Pernikahan kontrak penuh intrik dan bahaya.",
    motif: "💍 ⚔️",
  },
  "i-woke-up-married-to-koreas-coldest-idol": {
    themeColor: "#4F46E5",
    accentColor: "#38BDF8",
    gradient: "linear-gradient(135deg, #1E1B4B 0%, #0F172A 50%, #312E81 100%)",
    iconType: "idol",
    tagline: "Untouchable idol. Accidental bride.",
    taglineId: "Idol paling dingin. Pengantin tak terduga.",
    motif: "🎤 ✨",
  },
  "my-fake-boyfriend-is-actually-a-chaebol-heir": {
    themeColor: "#059669",
    accentColor: "#F59E0B",
    gradient: "linear-gradient(135deg, #064E3B 0%, #111827 50%, #022C22 100%)",
    iconType: "chaebol",
    tagline: "Hired mechanic. Billionaire empire heir.",
    taglineId: "Montir sewaan. Pewaris tahta konglomerat.",
    motif: "👑 💎",
  },
  "the-ceo-who-fired-me-became-my-fiance": {
    themeColor: "#DC2626",
    accentColor: "#FB7185",
    gradient: "linear-gradient(135deg, #450A0A 0%, #18181B 50%, #7F1D1D 100%)",
    iconType: "ceo",
    tagline: "Fired by 5 P.M. Engaged by 7 P.M.",
    taglineId: "Dipecat jam 5 sore. Tunangan jam 7 malam.",
    motif: "💼 🔥",
  },
  "i-accidentally-texted-a-superstar-at-2am": {
    themeColor: "#7C3AED",
    accentColor: "#F472B6",
    gradient: "linear-gradient(135deg, #2E1065 0%, #090A0F 50%, #4C1D95 100%)",
    iconType: "superstar",
    tagline: "One wrong text to Korea's top star.",
    taglineId: "Pesan salah kirim ke superstar ternama.",
    motif: "📱 🌙",
  },
  "my-enemy-bought-the-company-i-work-for": {
    themeColor: "#B45309",
    accentColor: "#FBBF24",
    gradient: "linear-gradient(135deg, #451A03 0%, #1C1917 50%, #78350F 100%)",
    iconType: "ceo",
    tagline: "University rival is now the boss.",
    taglineId: "Musuh masa kuliah kini menjadi bosku.",
    motif: "🏢 ⚡",
  },
  "the-idol-next-door-knows-my-secret": {
    themeColor: "#0284C7",
    accentColor: "#67E8F9",
    gradient: "linear-gradient(135deg, #082F49 0%, #030712 50%, #0C4A6E 100%)",
    iconType: "idol",
    tagline: "Ordinary accountant. Hit melody genius.",
    taglineId: "Karyawati biasa. Pencipta lagu hits rahasia.",
    motif: "🎧 🎶",
  },
  "i-signed-a-contract-to-date-koreas-most-hated-actor": {
    themeColor: "#9333EA",
    accentColor: "#E879F9",
    gradient: "linear-gradient(135deg, #3B0764 0%, #18181B 50%, #581C87 100%)",
    iconType: "superstar",
    tagline: "PR contract with a framed superstar.",
    taglineId: "Kontrak PR memacari aktor yang difitnah.",
    motif: "🎭 📸",
  },
  "my-ex-came-back-as-my-new-boss": {
    themeColor: "#EA580C",
    accentColor: "#FDBA74",
    gradient: "linear-gradient(135deg, #431407 0%, #0F172A 50%, #7C2D12 100%)",
    iconType: "romance",
    tagline: "First love returns with power.",
    taglineId: "Cinta pertama kembali sebagai pemimpin.",
    motif: "⏳ ❤️",
  },
  "the-heir-who-pretended-to-be-my-bodyguard": {
    themeColor: "#1E293B",
    accentColor: "#38BDF8",
    gradient: "linear-gradient(135deg, #020617 0%, #0F172A 50%, #1E293B 100%)",
    iconType: "bodyguard",
    tagline: "Tactical bodyguard. Undercover billionaire.",
    taglineId: "Pengawal tangguh. Miliarder menyamar.",
    motif: "🛡️ 💎",
  },
  "i-married-him-for-revenge-then-fell-first": {
    themeColor: "#BE123C",
    accentColor: "#FB7185",
    gradient: "linear-gradient(135deg, #4C0519 0%, #18181B 50%, #881337 100%)",
    iconType: "revenge",
    tagline: "Revenge vows turned to true passion.",
    taglineId: "Niat balas dendam berbuah cinta sejati.",
    motif: "🥀 🖤",
  },
  "my-sister-stole-my-fiance-so-i-married-his-rival": {
    themeColor: "#A21CAF",
    accentColor: "#F472B6",
    gradient: "linear-gradient(135deg, #4A044E 0%, #0C0A09 50%, #701A75 100%)",
    iconType: "revenge",
    tagline: "Betrayed bride marries the enemy tycoon.",
    taglineId: "Dikhianati adik, lalu menikahi sang raja bisnis.",
    motif: "👑 👠",
  },
  "the-superstar-who-forgot-everyone-except-me": {
    themeColor: "#2563EB",
    accentColor: "#60A5FA",
    gradient: "linear-gradient(135deg, #172554 0%, #0B132B 50%, #1E40AF 100%)",
    iconType: "superstar",
    tagline: "Amnesia idol remembers only one face.",
    taglineId: "Superstar amnesia hanya mengingat satu nama.",
    motif: "🌟 💭",
  },
  "i-became-the-villainess-in-his-scandal": {
    themeColor: "#991B1B",
    accentColor: "#FCA5A5",
    gradient: "linear-gradient(135deg, #450A0A 0%, #18181B 50%, #7F1D1D 100%)",
    iconType: "revenge",
    tagline: "Framed as the nation's home-wrecker.",
    taglineId: "Difitnah sebagai perusak hubungan selebriti.",
    motif: "🗞️ 🔥",
  },
  "my-blind-date-was-the-ceo-i-insulted-online": {
    themeColor: "#D97706",
    accentColor: "#FCD34D",
    gradient: "linear-gradient(135deg, #451A03 0%, #18181B 50%, #78350F 100%)",
    iconType: "ceo",
    tagline: "Worst blind date with online target.",
    taglineId: "Kencan buta dengan CEO yang dihina di internet.",
    motif: "⭐ ☕",
  },
  "the-idol-who-hates-cameras-only-smiles-for-me": {
    themeColor: "#0D9488",
    accentColor: "#5EEAD4",
    gradient: "linear-gradient(135deg, #042F2E 0%, #0B132B 50%, #115E59 100%)",
    iconType: "camera",
    tagline: "Cold star smiles only for her lens.",
    taglineId: "Idol dingin hanya tersenyum di depan kameranya.",
    motif: "📷 ✨",
  },
  "i-was-hired-to-break-his-heart": {
    themeColor: "#4338CA",
    accentColor: "#A5B4FC",
    gradient: "linear-gradient(135deg, #1E1B4B 0%, #18181B 50%, #312E81 100%)",
    iconType: "contract",
    tagline: "Paid to seduce him. Trapped in real love.",
    taglineId: "Dibayar menghancurkan hatinya, malah jatuh cinta.",
    motif: "💔 🕊️",
  },
  "the-man-in-apartment-1707-is-a-runaway-star": {
    themeColor: "#0369A1",
    accentColor: "#38BDF8",
    gradient: "linear-gradient(135deg, #082F49 0%, #090A0F 50%, #075985 100%)",
    iconType: "superstar",
    tagline: "Reclusive neighbor is missing top actor.",
    taglineId: "Tetangga apartemen ternyata superstar yang hilang.",
    motif: "🚪 🌌",
  },
  "i-rejected-a-billionaire-without-knowing-who-he-was": {
    themeColor: "#CA8A04",
    accentColor: "#FDE047",
    gradient: "linear-gradient(135deg, #422006 0%, #18181B 50%, #713F12 100%)",
    iconType: "chaebol",
    tagline: "Turned him down. He bought the company.",
    taglineId: "Ditolak di kafe, pria itu membeli perusahaannya.",
    motif: "🍸 💼",
  },
  "my-contract-husband-has-another-identity": {
    themeColor: "#6B21A8",
    accentColor: "#D8B4FE",
    gradient: "linear-gradient(135deg, #3B0764 0%, #0F172A 50%, #581C87 100%)",
    iconType: "mask",
    tagline: "Quiet accountant by day. Masked icon by night.",
    taglineId: "Akuntan pendiam siang hari, musisi bertopeng malam hari.",
    motif: "🎭 🌙",
  },
  "i-time-traveled-to-the-night-before-his-debut": {
    themeColor: "#0284C7",
    accentColor: "#F43F5E",
    gradient: "linear-gradient(135deg, #0C4A6E 0%, #1E1B4B 50%, #881337 100%)",
    iconType: "time",
    tagline: "Ten years back to save his destiny.",
    taglineId: "Sepuluh tahun ke masa lalu demi menyelamatkan takdirnya.",
    motif: "⏳ 🎤",
  },
};

export function getStoryCoverArt(slug: string): StoryCoverArt {
  return (
    STORY_COVERS[slug] || {
      themeColor: "#881337",
      accentColor: "#F43F5E",
      gradient: "linear-gradient(135deg, #4C0519 0%, #18181B 50%, #1E1B4B 100%)",
      iconType: "romance",
      tagline: "A dramatic visual journey.",
      taglineId: "Kisah drama visual memukau.",
      motif: "✨ 💖",
    }
  );
}
